name: Ask a Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release
        required: true

jobs:
  ask-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure GIT
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Release
        run: npm version ${{ github.event.inputs.version }}

      - name: Push changes
        run: git push --follow-tags

  send-release:
    needs: ask-release
    uses: ./.github/workflows/build.yml
    with:
      is-release: true

