name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release (e.g. 1.0.0)
        required: true

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Configure Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Bump version
        run: pnpm version "${{ github.event.inputs.version }}"

      - name: Push changes and tags
        run: git push --follow-tags

      - name: Create version file
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "v${VERSION}" > version

      - name: Upload version file
        uses: actions/upload-artifact@v6
        with:
          name: version
          path: version

  build-and-release:
    name: Build & release
    needs: prepare-release
    uses: ./.github/workflows/build.yml
    with:
      is-release: 'true'
    secrets: inherit

