name: Ask a Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release
        required: true

jobs:
  ask-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Install Node.js 26
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'pnpm'

      - name: Configure GIT
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Release
        run: npm version ${{ github.event.inputs.version }}

      - name: Push changes
        run: git push --follow-tags
        
      - name: Create version file
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo v${VERSION} >> version
      - name: Upload version file
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version

  send-release:
    needs: ask-release
    uses: ./.github/workflows/build.yml
    with:
      is-release: 'true'
    secrets: inherit

